### ISSUE TITLE
Game start Error

### ISSUE THREAD

**Issue by drizzerx** [LibsHungergames/LibsHungergames#18]
````
[18:46:59] [Server thread/WARN]: [LibsHungergames] Task #10 for LibsHungergames v5.7.2 generated an exception
java.lang.AssertionError: No sound with name ENDERMEN_TELEPORT or ENTITY_ENDERMAN_TELEPORT
	at net.techcable.hungergames.SafeSounds.<init>(SafeSounds.java:29) ~[?:?]
	at net.techcable.hungergames.SafeSounds.<clinit>(SafeSounds.java:13) ~[?:?]
	at me.libraryaddict.Hungergames.Hungergames.startGame(Hungergames.java:457) ~[?:?]
	at me.libraryaddict.Hungergames.Hungergames.onSecond(Hungergames.java:334) ~[?:?]
	at me.libraryaddict.Hungergames.Hungergames.access$200(Hungergames.java:46) ~[?:?]
	at me.libraryaddict.Hungergames.Hungergames$4.run(Hungergames.java:276) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
````

**Comment by Techcable** [comment]
Duplicate of #21
