### ISSUE TITLE
Forcestart error

### ISSUE THREAD

**Issue by drizzerx** [LibsHungergames/LibsHungergames#19]
````
[18:59:04 INFO]: DrizzerX issued server command: /forcestart
[18:59:04 INFO]: El juego ha empezado!
[18:59:04 INFO]: Invencibilidad desaparece en 1 minuto!
[18:59:04 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'forcestart' in plugin LibsHungergames v5.7.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.AssertionError: No sound with name ENDERMEN_TELEPORT or ENTITY_ENDERMAN_TELEPORT
        at net.techcable.hungergames.SafeSounds.<init>(SafeSounds.java:29) ~[?:?]
        at net.techcable.hungergames.SafeSounds.<clinit>(SafeSounds.java:13) ~[?:?]
        at me.libraryaddict.Hungergames.Hungergames.startGame(Hungergames.java:457) ~[?:?]
        at me.libraryaddict.Hungergames.Commands.ForceStartCommand.onCommand(ForceStartCommand.java:53) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
        ... 15 more
````

**Comment by Techcable** [comment]
Duplicate of #21
